#!/bin/sh

CONF_PATH=/conf
CONF_FILE=$CONF_PATH/supernode.conf
CONF_EXAMPLE=/etc/n2n/supernode.conf.sample
CONF_EXAMPLE_OUTPUT=$CONF_PATH/supernode.conf.sample

if test -f "$CONF_FILE"; then
    edge $CONF_FILE -f
else
    echo "config file: $CONF_FILE not exist"
    echo "please add config files to /conf"
    mkdir -p /conf
    cp $CONF_EXAMPLE $CONF_EXAMPLE_OUTPUT
    echo "see /conf/supernode.conf.example"
fi
